#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t havoc"

$L "**********************************************" 
$L "                                              " 
$L "      dMP dMP .aMMMb  dMP dMP .aMMMb  .aMMMb  " 
$L "     dMP dMP dMP'dMP dMP dMP dMP'dMP dMP'VMP  " 
$L "    dMMMMMP dMMMMMP dMP dMP dMP dMP dMP       " 
$L "   dMP dMP dMP dMP  YMvAP' cMP.aMP dMP.aMP    " 
$L "  dMP dMP dMP dMP    VP'   VMMMP'  VMMMP'     " 
$L "                                              " 
$L "**********************************************" 
$L "*************** Android 9.0 Pie **************" 
$L "************* Welcome to Havoc-OS ************" 
$L "**********************************************" 
$L `getprop ro.build.version.release` / Havoc-OS-`getprop ro.havoc.version`";
