#!/system/bin/sh
log -p i -t start "**********************************************"); 
log -p i -t start "                                              "); 
log -p i -t start "      dMP dMP .aMMMb  dMP dMP .aMMMb  .aMMMb  "); 
log -p i -t start "     dMP dMP dMP'dMP dMP dMP dMP'dMP dMP'VMP  "); 
log -p i -t start "    dMMMMMP dMMMMMP dMP dMP dMP dMP dMP       "); 
log -p i -t start "   dMP dMP dMP dMP  YMvAP' cMP.aMP dMP.aMP    "); 
log -p i -t start "  dMP dMP dMP dMP    VP'   VMMMP'  VMMMP'     "); 
log -p i -t start "                                              "); 
log -p i -t start "**********************************************"); 
log -p i -t start "******************* Team Z *******************"); 
log -p i -t start "************* Welcome to Havoc-OS ************"); 
log -p i -t start "**********************************************");
